# Generated by Django 2.2.8 on 2020-09-16 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(blank=True, max_length=100, verbose_name='学校')),
                ('comany', models.CharField(blank=True, max_length=100, verbose_name='公司')),
                ('profession', models.CharField(blank=True, max_length=100, verbose_name='专业')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='地址')),
                ('aboutme', models.TextField(blank=True, verbose_name='个人介绍')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'UserInfo',
                'verbose_name_plural': 'UserInfos',
            },
        ),
    ]
