# Generated by Django 2.2.8 on 2020-09-16 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200916_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='comany',
            new_name='company',
        ),
    ]
